# Group Звонок
Средствами JSON API можно создавать и обновлять сведения о звонках, а так же направлять события карточки звонка.

## Создать звонок [/call]
### Создать звонок [POST]

Создать новый звонок
### Описание
Звонок создаётся на основе переданного объекта JSON,
который содержит представление нового Звонка.
Поле **counterparty**, при его заполнении, приоритетнее чем **number**. 
Поле **employee**, при его заполнении, приоритетнее чем **extension**.
Поле **endTime**, при его заполнении, приоритетнее чем **duration**.

+ **externalId** - `Необходимое` Внешний ID звонка
+ **number** - `Необходимое` Внешний номер телефона
+ **counterparty** - Ссылка на Контрагента, с которым связан звонок в формате [Метаданных](#header-метаданные)
+ **extension** - Добавочный номер пользователя, который совершил звонок, или который привязан к звонку
+ **employee** - Сотрудник, с которым связан звонок, в формате [Метаданных](#header-метаданные)
+ **isIncoming** - `Необходимое` Направление звонка: входящий (true) или исходящий(false)
+ **startTime** - `Необходимое` Время начала разговора: время в ISO формате (yyyy-MM-dd HH:mm:ss.SSS)
+ **endTime** - Время окончания разговора: время в ISO формате (yyyy-MM-dd HH:mm:ss.SSS)
+ **duration** - Продолжительность вызова в миллисекундах
+ **recordUrl** - Массив URL записей разговоров
+ **events** - Список событий карточки звонка для обработки
  + **eventType** - `Необходимое`  Тип события (SHOW, STARTTIME, HIDE)
  + **extension** - `Необходимое`  Добавочный номер
  + **sequence** - `Необходимое`  Порядковый номер события
  + **employee** - Сотрудник, которому предназначена нотификация, в формате [Метаданных](#header-метаданные)
+ **comment** - Комментарий к звонку. Строка, не более 4096 символов (слишком длинная строка обрезается).

+ Request Пример 1 (application/json)
Пример полного запроса для создания Звонка.
  + Headers
    Lognex-Phone-Auth-Token: d03627d59c1948a0f9a6aa1e267c954bfd0301ec

  + Body

            <!-- include(body/call/post_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного звонка.
  + Body

            <!-- include(body/call/post_response.json) -->

## Получить звонок [/call/{id}]
+ Parameters
  + id: `89fc07ad-2c8d-11e6-8a84-bae500000051` (required, string) - id Звонка.

### Получить звонок [GET]
Возвращает JSON представление Звонка с указанным id.

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Звонка с указанным id.
  + Headers
    Lognex-Phone-Auth-Token: d03627d59c1948a0f9a6aa1e267c954bfd0301ec

  + Body

            <!-- include(body/call/get_by_id_response.json) -->

## Изменить звонок [/call/{id}]
+ Parameters
  + id: `89fc07ad-2c8d-11e6-8a84-bae500000051` (required, string) - id Звонка.

### Изменить звонок [PUT]
### Описание
Обновляется представление Звонка с указанным id.
В теле запроса можно указать только те поля, которые необходимо изменить у Звонка.
Поля, которые не были указаны в JSON запроса, не изменяются, поля уже заполненные у сущности не перезаписываются (за исключением **comment**).
Поле **recordUrl** добавляет данные к сущности.
Поле **comment** обновляется, только если не null.
Поле **employee**, при его заполнении, приоритетнее чем **extension**.
Поле **endTime**, при его заполнении, приоритетнее чем **duration**.

+ **extension** - Добавочный номер пользователя, который совершил звонок, или который привязан к звонку
+ **employee** - Сотрудник, с которым связан звонок, в формате [Метаданных](#header-метаданные)
+ **endTime** - Время окончания разговора: время в ISO формате (yyyy-MM-dd HH:mm:ss.SSS)
+ **duration** - Продолжительность вызова в миллисекундах
+ **recordUrl** - Массив URL записей разговоров
+ **events** - Список событий карточки звонка для обработки
  + **eventType** - `Необходимое`  Тип события
    + **SHOW** - Показать карточку звонка
    + **STARTTIME** - Запустить таймер карточки
    + **HIDE** - Скрыть карточку звонка
    + **HIDE_ALL** - Скрыть карточки для всех участников звонка
  + **extension** - `Необходимое`  Добавочный номер. Для типа события **HIDE_ALL** не является обязательным
  + **sequence** - `Необходимое`  Порядковый номер события
  + **employee** - Сотрудник, которому предназначена нотификация, в формате [Метаданных](#header-метаданные)
+ **comment** - Комментарий к звонку. Может быть обновлен любое количество раз, null - не обновлять поле.


+ Request Пример (application/json)
В теле запроса можно указать только те поля, которые необходимо изменить у звонка
+ Headers
    Lognex-Phone-Auth-Token: d03627d59c1948a0f9a6aa1e267c954bfd0301ec

  + Body

            <!-- include(body/call/put_request.json) -->

+ Response 200 (application/json)
Успешное обновление. Результат - JSON представление обновлённого звонка.
  + Body

            <!-- include(body/call/put_response.json) -->
	  

## Изменить звонок по внешнему ID [/call/extid/{extid}]

+ Parameters
  + extid: `AjllkmSAkml` (required, string) - Внешний id Звонка.
  
### Изменить звонок по внешнему ID[PUT]
### Описание
Обновляется представление Звонка с указанным extid.
В теле запроса можно указать только те поля, которые необходимо изменить у Звонка.
Поля, которые не были указаны в JSON запроса, не изменяются, поля уже заполненные у сущности не перезаписываются (за исключением **comment**).
Поле **recordUrl** добавляет данные к сущности.
Поле **comment** обновляется, только если не null.

+ **extension** - Добавочный номер пользователя, который совершил звонок, или который привязан к звонку
+ **employee** - Сотрудник, с которым связан звонок, в формате [Метаданных](#header-метаданные)
+ **endTime** - Время окончания разговора: время в ISO формате (yyyy-MM-dd HH:mm:ss.SSS)
+ **duration** - Продолжительность вызова в миллисекундах
+ **recordUrl** - Массив URL записей разговоров
+ **events** - Список событий карточки звонка для обработки
  + **eventType** - `Необходимое`  Тип события
    + **SHOW** - Показать карточку звонка
    + **STARTTIME** - Запустить таймер карточки
    + **HIDE** - Скрыть карточку звонка
    + **HIDE_ALL** - Скрыть карточки для всех участников звонка
  + **extension** - `Необходимое`  Добавочный номер. Для типа события **HIDE_ALL** не является обязательным
  + **sequence** - `Необходимое`  Порядковый номер события
  + **employee** - Сотрудник, которому предназначена нотификация, в формате [Метаданных](#header-метаданные)
+ **comment** - Комментарий к звонку. Может быть обновлен любое количество раз, null - не обновлять поле.

+ Request Пример (application/json)
В теле запроса можно указать только те поля, которые необходимо изменить у звонка
  + Headers
    Lognex-Phone-Auth-Token: d03627d59c1948a0f9a6aa1e267c954bfd0301ec

  + Body

            <!-- include(body/call/put_request.json) -->

+ Response 200 (application/json)
Успешное обновление. Результат - JSON представление обновлённого звонка.
  + Body

            <!-- include(body/call/put_response.json) -->

##Событие карточки звонка по внутреннему id [/call/{id}/event]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Звонка.

###Послать событие карточки звонка по внутреннему id [POST]
Посылает событие карточки звонка.
  + **eventType** - `Необходимое`  Тип события
    + **SHOW** - Показать карточку звонка
    + **STARTTIME** - Запустить таймер карточки
    + **HIDE** - Скрыть карточку звонка
    + **HIDE_ALL** - Скрыть карточки для всех участников звонка
  + **extension** - `Необходимое`  Добавочный номер. Для типа события *HIDE_ALL* не является обязательным
  + **sequence** - `Необходимое`  Порядковый номер события
  + **employee** - Сотрудник, которому предназначена нотификация, в формате [Метаданных](#header-метаданные)

+ Request Пример (application/json)
  + Headers
    Lognex-Phone-Auth-Token: d03627d59c1948a0f9a6aa1e267c954bfd0301ec

  + Body

            <!-- include(body/call/post_event_request.json) -->

+ Response 204 (application/json)
Успешный запрос.
  + Body

##Событие карточки звонка по внешнему id [/call/extid/{extid}/event]
+ Parameters
  + extid: `AjllkmSAkml` (required, string) - Внешний id Звонка.

### Послать событие карточки звонка по внешнему id[POST]
Посылает событие карточки звонка.
  + **eventType** - `Необходимое`  Тип события
    + **SHOW** - Показать карточку звонка
    + **STARTTIME** - Запустить таймер карточки
    + **HIDE** - Скрыть карточку звонка
    + **HIDE_ALL** - Скрыть карточки для всех участников звонка
  + **extension** - `Необходимое`  Добавочный номер. Для типа события *HIDE_ALL* не является обязательным
  + **sequence** - `Необходимое`  Порядковый номер события
  + **employee** - Сотрудник, которому предназначена нотификация, в формате [Метаданных](#header-метаданные)

+ Request Пример (application/json)
  + Headers
    Lognex-Phone-Auth-Token: d03627d59c1948a0f9a6aa1e267c954bfd0301ec

  + Body

            <!-- include(body/call/post_event_request.json) -->

+ Response 204 (application/json)
Успешный запрос.
  + Body
