# Group Сотрудники
Средствами JSON API можно получать список сотрудников, обладающих добавочным номером, с возможностью фильтрации результата.

## Найти сотрудников с добавочным номером [/employee?filter={filter}]
+ Parameters
  + filter: `extention=1234` (optional, string) - фильтр в запросе.
### Найти сотрудников с добавочным номером [GET]
Ищем сотрудников с добавочным номером с возможностью фильтрации в запросе по нему.
Тело запроса пусто.
Параметры фильтрации описаны в [разделе фильтрации](#header-фильтрация-выборки-с-помощью-параметра-filter)

+ Request Пример (application/json)
  + Headers
    Lognex-Phone-Auth-Token: d03627d59c1948a0f9a6aa1e267c954bfd0301ec

+ Response 200 (application/json)
Успешный поиск. Результат - JSON представление сотрудника.
  + Body

            <!-- include(body/example/employee_by_filter_response.json) -->
