

<h3><a name="обработка-ошибок-1000"></a>1000</h3>
+ **Сообщение**: *Элемент URI не является идентификатором*
+ **Описание**: Вероятнее всего вы пытаетесь обратиться к несуществующему ресурсу. Проверьте
  указанный вами URI, проверьте правильно ли вы указали ключевое слово сущности и полностью ли вы скопировали ID.

<h3><a name="обработка-ошибок-1002"></a>1002</h3>
+ **Сообщение**: *Неопознанный путь: {путь}*
+ **Описание**: Не удалось определить ресурс, по которому был сделан запрос. Проверьте URI по которому совершается запрос.

<h3><a name="обработка-ошибок-1021"></a>1021</h3>
+ **Сообщение**: *Объект с типом '{тип}' и идентификатором '{id}' не найден*
+ **Описание**: Не удалось загрузить сущность данного типа с данным id. Проверьте корректность id. Убедитесь что сущность с данным id присутствует среди списка сущностей данного типа (возможно сущность с данным id была удалена)

<h3><a name="обработка-ошибок-1034"></a>1034</h3>
+ **Сообщение**: *Ошибка фильтрации: '{описание ошибки}'*
+ **Описание**: Не удалось отфильтровать сущности по заданному параметру. Проверьте корректность запроса.

<h3><a name="обработка-ошибок-1037"></a>1037</h3>
+ **Сообщение**: *Неверно указан Content-Type запроса*
+ **Описание** Возможно ресурс, к которому вы обращаетесь, требует form-data вместо JSON (или наоборот).

<h3><a name="обработка-ошибок-1039"></a>1039</h3>
+ **Сообщение**: *Операция {HTTP метод} не поддерживается для данного ресурса*
+ **Описание** Проверьте метод, с которым вы обращаетесь к ресурсу. Убедитесь, что в документации ресурса этот метод описан и его можно применить.

<h3><a name="обработка-ошибок-1040"></a>1040</h3>
+ **Сообщение**: *Неверно заданы параметры запроса*
+ **Описание** Один или несколько параметров запроса заданы некорректно. Проверьте формат параметров согласно документации.

<h3><a name="обработка-ошибок-1044"></a>1044</h3>
+ **Сообщение**: *Превышен максимальный размер запроса*
+ **Описание**: Максимальный размер запроса 10 МБ.

<h3><a name="обработка-ошибок-1051"></a>1051</h3>
+ **Сообщение**: *Тип <type> не совпадает с типом <meta_type> из meta*
+ **Описание** Тип, который вы указали в объекте **meta** не соответствует типу ресурса, к которому вы делаете запрос.

<h3><a name="обработка-ошибок-1052"></a>1052</h3>
+ **Сообщение**: *Неверный формат UUID*
+ **Описание**: Проверьте сгенерированные вами UUID на корректность.

<h3><a name="обработка-ошибок-1056"></a>1056</h3>
+ **Сообщение**: *Ошибка аутентификации: {текст ошибки аутентификации}*
+ **Описание** Проверьте указанные для аутентификации данные. Возможно для данного ресурса требуется другой вид аутентификации.

<h3><a name="обработка-ошибок-1060"></a>1060</h3>
+ **Сообщение**: *Некорректный тип данных в meta сущности, поле type*
+ **Описание** Тип данных указанный в поле type метаданных сущности не совпадает с ожидаемым типом.

<h3><a name="обработка-ошибок-1062"></a>1062</h3>
+ **Сообщение**: *Неверное значение заголовка 'Accept'. Поддерживается только значение 'application/json;charset=utf-8'*
+ **Описание** Значение заголовка 'Accept' может быть только application/json;charset=utf-8.

<h3><a name="обработка-ошибок-1065"></a>1065</h3>
+ **Сообщение**: *Ошибка сохранения объекта: объект уже изменен/удален в параллельном запросе*
+ **Описание** Ошибка возникает при попытке изменить объект из нескольких параллельных запросов к API.

<h3><a name="обработка-ошибок-1074"></a>1074</h3>
+ **Сообщение**: *Сервис временно недоступен, ведутся технические работы*
+ **Описание** На сервере проводятся технические работы.

<h3><a name="обработка-ошибок-1999"></a>1999</h3>
+ **Сообщение**: *Неизвестная ошибка*
+ **Описание** Произошла непредвиденная ошибка. Пожалуйста, обратитесь в поддержку сервиса МойСклад подробно изложив условия при которых эта ошибка произошла.

<h3><a name="обработка-ошибок-2001"></a>2001</h3>
+ **Сообщение**: *Ошибка формата: входящий запрос не соответствует формату JSON*
+ **Описание**: Данные должны быть отправлены в формате JSON. Если это так, а ошибка всё-таки возникает - попробуйте добавить Header `Content-Type` со значением `application/json`.

<h3><a name="обработка-ошибок-2005"></a>2005</h3>
+ **Сообщение**: *Ошибка формата: входящий JSON должен начинаться либо с объекта, либо с массива*
+ **Описание**: Отсутствует открывающаяся фигурная/квадратная скобка в начале тела запроса.

<h3><a name="обработка-ошибок-2009"></a>2009</h3>
+ **Сообщение**: *Ошибка формата: запрос на создание/обновление одной сущности не должен содержать массив*
+ **Описание**: При обновлении отдельной сущности подразумевается, что в теле запроса будет передано её новое представление (одно). В теле запроса должен быть один корневой объект.

<h3><a name="обработка-ошибок-2010"></a>2010</h3>
+ **Сообщение**: *Ошибка формата: отсутствует href для meta поля '{доп. сообщение}'*
+ **Описание**: В переданном объекте метаданных отсутствует поле **href**. Проверьте тело запроса.

<h3><a name="обработка-ошибок-2011"></a>2011</h3>
+ **Сообщение**: *Ошибка формата: отсутствует type для meta поля '{доп. сообщение}'*
+ **Описание**: В переданном объекте метаданных отсутствует поле **type**. Проверьте тело запроса.

<h3><a name="обработка-ошибок-2013"></a>2013</h3>
+ **Сообщение**: *Ошибка формата: неправильное значение href для meta поля '{доп. сообщение}'*
+ **Описание**: Переданный **href** указывает на несуществующий объект. Убедитесь в корректности ссылки. Ошибка может быть в версии API, типе ресурса (entity/pos/report), ключевом слове сущности/(отчёта), id сущности.

<h3><a name="обработка-ошибок-2017"></a>2017</h3>
+ **Сообщение**: *Ошибка формата: неизвестная ошибка*
+ **Описание**: Не удалось однозначно классифицировать ошибку. Убедитесь что формат передаваемых вами данных соответствует требуемому. Посмотрите примеры запросов в документации по используемой вами сущности.

<h3><a name="обработка-ошибок-3000"></a>3000</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не может быть пустым или отсутствовать*
+ **Описание**: Необходимое поле не может содержать пустого значения или отсутствовать. Все необходимые поля можно посмотреть в документации по сущности, с которой вы работаете, под заголовком "Атрибуты сущности". Такие поля помечены как `Необходимое`.

<h3><a name="обработка-ошибок-3005"></a>3005</h3>
+ **Сообщение**: *Ошибка сохранения объекта: неверное значение '{значение}' поля '{имя поля}'. Допустимые значения: {список значений}*
+ **Описание**: Вы пытаетесь присвоить несуществующее значение полю типа "перечисление"(enum). Проверить все возможные значения этого поля вы можете в документации по данной сущности в разделе "Атрибуты сущности".

<h3><a name="обработка-ошибок-3006"></a>3006</h3>
+ **Сообщение**: *Ошибка сохранения объекта: нарушено ограничение уникальности параметра '{имя параметра}'*
+ **Описание**: У указанного поля/параметра должно быть уникальное значение в системе. Например, если включена проверка на уникальность номеров операций, `name` у разных документов не может быть одинаковым.

<h3><a name="обработка-ошибок-3007"></a>3007</h3>
+ **Сообщение**: *Ошибка валидации сохраняемого объекта: '{доп. сообщение}'*
+ **Описание**: Ошибка при обмене. Проверьте, соблюдает ли все условия передаваемый вами объект.

<h3><a name="обработка-ошибок-3045"></a>3045</h3>
+ **Сообщение**: *Ошибка валидации: указан неактивный пользователь*
+ **Описание**: Указанный сотрудник является неактивным. Например, при создании ему не был задан логин.

<h3><a name="обработка-ошибок-55008"></a>55008</h3>
+ **Сообщение**: *Не установлено решение для работы c '{наименование API}'*
+ **Описание**: Для работы с ресурсом необходимо установить решение из списка решений МоегоСклада.
