# Group Требования к провайдеру телефонии
В рамках интеграции провайдеру телефонии необходимо реализовать обработку запроса для инициации исходящего вызова. В http заголовке передается подпись, которая генерируется на основе алгоритма md5, на вход которого подается конкатенация ключа доступа пользователя и значений параметров запроса.

##  Исходящий вызов [/some_url]
### nourl Исходящий вызов [POST]

+ **srcNumber** - номер, с которого производится исходящий вызов
+ **destNumber** - номер телефона, на который происходит звонок
+ **uid** - логин сотрудника, совершающего вызов

+ Request Пример 1 (application/json)
Пример полного запроса для создания Звонка.

  + Headers
            Lognex-Content-MD5: 802EFD4A933386248031D2928612A13F

  + Body

            <!-- include(body/outgoingcall/call_request.json) -->

+ Response 200 (application/json)
Успешный запрос.
  + Body

