name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          ./build.sh
