name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        env:
          SERVER_IP_ADDRESS: dev.moysklad.ru
          APP_PREFIX: api-phone
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ./build.sh
          ls output
